config/routes.rb
Rails.application.routes.draw do
  resources :intents
  resources :entries
  resources :entities
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations" }

  resources :chats
  resources :companies
  resources :categories

  get  'invites/index' => 'invites#index', as: 'invites'
  post 'invites/invite' => 'invites#invite', as: 'invite'

  root 'pages#index'

  post '/chats/webhook' => 'chats#webhook'
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :entity
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url, notice: 'Entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:name, :entity_id)
    end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_form.html.slim
= simple_form_for @entry, html: { class: "form-horizontal" }, wrapper: :horizontal_form, wrapper_mappings: { check_boxes: :horizontal_radio_and_checkboxes, radio_buttons: :horizontal_radio_and_checkboxes, file: :horizontal_file_input, boolean: :horizontal_boolean } do |f|
  = f.input :name
  = f.input :entity_id
  .form-group
    .col-sm-offset-3.col-sm-9
      = f.submit nil, class: 'btn btn-primary'
      = link_to t('.cancel', default: t("helpers.links.cancel")), entries_path, class: 'btn btn-default'

app/views/entries/edit.html.slim
- model_class = Entry
div class="page-header"
  h1=t '.title', default: [:'helpers.titles.edit', 'Edit %{model}'], model: model_class.model_name.human.titleize
= render partial: "form"

app/views/entries/index.html.slim
.page-header
  h1 Entries

.row
  .col-md-12
    ul.list-group
      - @entries.each do |entry|
        li.list-group-item
          strong= link_to entry.name, entry_path(entry)

          .pull-right
            / = link_to 'Add Question', new_chat_path(category_id: category.id), class: "btn btn-sm btn-primary"
            = link_to entry_path(entry), class: 'btn btn-xs', title: "#{ t('.show', default: t('helpers.links.show')) }" do
              = glyph 'info-sign'
            = link_to edit_entry_path(entry), class: 'btn btn-xs', title: "#{ t('.edit', default: t('helpers.links.edit')) }" do
              = glyph 'pencil'
            = link_to entry_path(entry), method: :delete, data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-xs', title: "#{ t('.destroy', default: t('helpers.links.destroy')) }" do
              = glyph 'remove'
  hr
  = link_to "Add new entry", new_entry_path, class: 'btn btn-success'

app/views/entries/new.html.slim
- model_class = Entry
.page-header
  h1=t '.title', default: [:'helpers.titles.new', 'New %{model}'], model: model_class.model_name.human.titleize
= render partial: "form"

app/views/entries/show.html.slim
- model_class = Entry
div class="page-header"
  h1=t '.title', default: model_class.model_name.human.titleize

.fieldset
  dl
      dt.label.label-default= model_class.human_attribute_name(:name)
      dd
        pre.prettyprint= @entry.name
      dt.label.label-default= model_class.human_attribute_name(:entity_id)
      dd
        pre.prettyprint= @entry.entity_id

.form-group
  = link_to t('.back', default: t("helpers.links.back")), entries_path, class: 'btn btn-default'
  '
  = link_to t('.edit', default: t("helpers.links.edit")), edit_entry_path(@entry), class: 'btn btn-default'
  '
  = link_to t('.destroy', default: t("helpers.links.destroy")), entry_path(@entry), method: "delete", data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-danger'