config/routes.rb
Rails.application.routes.draw do
  resources :intents
  resources :entries
  resources :entities
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations" }

  resources :chats
  resources :companies
  resources :categories

  get  'invites/index' => 'invites#index', as: 'invites'
  post 'invites/invite' => 'invites#invite', as: 'invite'

  root 'pages#index'

  post '/chats/webhook' => 'chats#webhook'
end

app/models/entity.rb
class Entity < ApplicationRecord
  has_many :entries, inverse_of: :entity, dependent: :destroy
  accepts_nested_attributes_for :entries, reject_if: :all_blank, allow_destroy: true

  validates :name, presence: true, uniqueness: true
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :set_entity, only: [:show, :edit, :update, :destroy]
  before_action :set_api_ai_client, only: [:create, :update, :destroy]

  # GET /entities
  # GET /entities.json
  def index
    @entities = Entity.all
  end

  # GET /entities/1
  # GET /entities/1.json
  def show
  end

  # GET /entities/new
  def new
    @entity = Entity.new
  end

  # GET /entities/1/edit
  def edit
  end

  # POST /entities
  # POST /entities.json
  def create
    uer = @api_ai_client.create_entities_request
    response = uer.create(param_options)

    @entity = Entity.new(entity_params)

    respond_to do |format|
      if response.is_a?(Hash) && response[:status][:code].eql?(200)
        @entity.entityId = response[:id]
        if @entity.save
          format.html { redirect_to @entity, notice: 'Entity was successfully created.' }
          format.json { render :show, status: :created, location: @entity }
        else
          format.html { render :new }
          format.json { render json: @entity.errors, status: :unprocessable_entity }
        end
      else
        format.html { redirect_to new_entity_path, alert: 'Failed to create entity.'}
      end
    end
  end

  # PATCH/PUT /entities/1
  # PATCH/PUT /entities/1.json
  def update
    param_opt = param_options("update")
    uer = @api_ai_client.create_entities_request
    response = uer.update(entity_params[:name].downcase.tr(" ","_"), param_opt)
    respond_to do |format|
      if response.is_a?(Hash) && response[:status][:code].eql?(200)
        if @entity.update(entity_params)
          format.html { redirect_to @entity, notice: 'Entity was successfully updated.' }
          format.json { render :show, status: :ok, location: @entity }
        else
          format.html { render :edit }
          format.json { render json: @entity.errors, status: :unprocessable_entity }
        end
      else
        format.html { redirect_to @entity, alert: 'Failed to update entity.'}
      end
    end
  end

  def destroy
    uer = @api_ai_client.create_entities_request
    response = uer.delete(@entity.entityId)

    respond_to do |format|
      if response.is_a?(Hash) && response[:status][:code].eql?(200)
        @entity.destroy
        format.html { redirect_to entities_url, notice: 'Entity was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { redirect_to @entity, alert: 'Failed to delete entity.'}
      end
    end
  end

  def param_options(upd = "")
    entries_data = []
    if entity_params[:entries_attributes].nil?
      entity_params[:entries_attributes] = "0"
    else
      entity_params[:entries_attributes].each do |k, us|
        entries_data << ApiAiRuby::Entry.new(us[:name], synonyms = [us[:name]])
      end
    end
    if upd == "update"
      param_options = (entries_data)
    else
      param_options = ApiAiRuby::Entity.new(entity_params[:name].downcase.tr(" ","_"), entries_data)
    end
    param_options
  end
  # DELETE /entities/1
  # DELETE /entities/1.json

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entity
      @entity = Entity.find(params[:id])
    end

    def set_api_ai_client
      @api_ai_client = ApiAiRuby::Client.new(:client_access_token => ENV['API_AI_ACCESS'])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def entity_params
      params.require(:entity).permit(:name, :company_id, entries_attributes: [:id, :name, :_destroy])
    end
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/views/entities/_entry_fields.html.slim
.nested-fields
	.page-header
		strong Entry
	br
	= f.input :name
	= link_to_remove_association "Remove parameter", f, class: "btn btn-sm btn-danger pull-right"

app/views/entities/_form.html.slim
= simple_form_for @entity, html: { class: "form-horizontal" }, wrapper: :horizontal_form, wrapper_mappings: { check_boxes: :horizontal_radio_and_checkboxes, radio_buttons: :horizontal_radio_and_checkboxes, file: :horizontal_file_input, boolean: :horizontal_boolean } do |f|
  = f.input :name
  = f.input :company_id, input_html: { value: current_user[:company_id] }, as: :hidden
  
  #intentUserSays
    = f.simple_fields_for :entries do |entry|
      = render 'entry_fields', f: entry

  .col-md-12
    = link_to_add_association 'Add Entry', f, :entries, class: "btn btn-sm btn-success"
    br
    br

  .clearfix

  .form-group
    .col-sm-offset-3.col-sm-9
      = f.submit nil, class: 'btn btn-primary'
      = link_to t('.cancel', default: t("helpers.links.cancel")), entities_path, class: 'btn btn-default'

app/views/entities/edit.html.slim
- model_class = Entity
div class="page-header"
  h1=t '.title', default: [:'helpers.titles.edit', 'Edit %{model}'], model: model_class.model_name.human.titleize
= render partial: "form"

app/views/entities/index.html.slim
.page-header
  h1 Entities

.row
  .col-md-12
    ul.list-group
      - @entities.each do |entity|
        li.list-group-item
          strong= link_to entity.name, entity_path(entity)

          .pull-right
            / = link_to 'Add Question', new_chat_path(category_id: category.id), class: "btn btn-sm btn-primary"
            = link_to entity_path(entity), class: 'btn btn-xs', title: "#{ t('.show', default: t('helpers.links.show')) }" do
              = glyph 'info-sign'
            = link_to edit_entity_path(entity), class: 'btn btn-xs', title: "#{ t('.edit', default: t('helpers.links.edit')) }" do
              = glyph 'pencil'
            = link_to entity_path(entity), method: :delete, data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-xs', title: "#{ t('.destroy', default: t('helpers.links.destroy')) }" do
              = glyph 'remove'
  hr
  = link_to "Add new entity", new_entity_path, class: 'btn btn-success'

app/views/entities/new.html.slim
- model_class = Entity
.page-header
  h1=t '.title', default: [:'helpers.titles.new', 'New %{model}'], model: model_class.model_name.human.titleize
= render partial: "form"

app/views/entities/show.html.slim
- model_class = Entity
div class="page-header"
  h1=t '.title', default: model_class.model_name.human.titleize

.fieldset
  dl
      dt.label.label-default= model_class.human_attribute_name(:name)
      dd
        pre.prettyprint= @entity.name
  - @entity.entries.each do |entry|
    dl
      dt.label.label-default Entry Name
      dd
        pre.prettyprint= entry.name
    

.form-group
  = link_to t('.back', default: t("helpers.links.back")), entities_path, class: 'btn btn-default'
  '
  = link_to t('.edit', default: t("helpers.links.edit")), edit_entity_path(@entity), class: 'btn btn-default'
  '
  = link_to t('.destroy', default: t("helpers.links.destroy")), entity_path(@entity), method: "delete", data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-danger'