config/routes.rb
Rails.application.routes.draw do
  resources :intents
  resources :entries
  resources :entities
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations" }

  resources :chats
  resources :companies
  resources :categories

  get  'invites/index' => 'invites#index', as: 'invites'
  post 'invites/invite' => 'invites#invite', as: 'invite'

  root 'pages#index'

  post '/chats/webhook' => 'chats#webhook'
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :category
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :set_chat, only: [:show, :edit, :update, :destroy]
  protect_from_forgery with: :null_session

  # GET /chats
  # GET /chats.json
  def index
    @chats = Chat.all
  end

  # GET /chats/1
  # GET /chats/1.json
  def show
  end

  def webhook
    if params[:result][:parameters][:number].nil? || params[:result][:parameters][:number] == ""
      response = "Oops, I didn't get that."
      render json: { speech: response, displayText: response, source: "chatbot-platform.herokuapp.com" }, status: :ok
    else
      if params[:result][:parameters][:shipping].nil? || params[:result][:parameters][:shipping] == ""
        response = "Your order with id " + params[:result][:parameters][:number] + " is being shipped."
        render json: { speech: response, displayText: response, source: "chatbot-platform.herokuapp.com" }, status: :ok
      else
        response = "Your order with id " + params[:result][:parameters][:number] + " payment is completed."
        render json: { speech: response, displayText: response, source: "chatbot-platform.herokuapp.com" }, status: :ok
      end
    end
  end

  # GET /chats/new
  def new
    @chat = Chat.new
  end

  # GET /chats/1/edit
  def edit
  end

  # POST /chats
  # POST /chats.json
  def create
    @chat = Chat.new(chat_params)

    respond_to do |format|
      if @chat.save
        format.html { redirect_to @chat, notice: 'Chat was successfully created.' }
        format.json { render :show, status: :created, location: @chat }
      else
        format.html { render :new }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chats/1
  # PATCH/PUT /chats/1.json
  def update
    respond_to do |format|
      if @chat.update(chat_params)
        format.html { redirect_to @chat, notice: 'Chat was successfully updated.' }
        format.json { render :show, status: :ok, location: @chat }
      else
        format.html { render :edit }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chats/1
  # DELETE /chats/1.json
  def destroy
    @chat.destroy
    respond_to do |format|
      format.html { redirect_to chats_url, notice: 'Chat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chat
      @chat = Chat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chat_params
      params.require(:chat).permit(:question, :answer, :state, :category_id)
    end
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/views/chats/_form.html.slim
= simple_form_for @chat, html: { class: "form-horizontal" }, wrapper: :horizontal_form, wrapper_mappings: { check_boxes: :horizontal_radio_and_checkboxes, radio_buttons: :horizontal_radio_and_checkboxes, file: :horizontal_file_input, boolean: :horizontal_boolean } do |f|
  = f.input :question
  = f.input :answer
  = f.input :state
  = f.input :category_id, input_html: { value: params[:category_id]}, as: :hidden
  .form-group
    .col-sm-offset-3.col-sm-9
      = f.submit nil, class: 'btn btn-primary'
      = link_to t('.cancel', default: t("helpers.links.cancel")), chats_path, class: 'btn btn-default'

app/views/chats/edit.html.slim
- model_class = Chat
div class="page-header"
  h1=t '.title', default: [:'helpers.titles.edit', 'Edit %{model}'], model: model_class.model_name.human.titleize
= render partial: "form"

app/views/chats/index.html.slim
- model_class = Chat
.page-header
  h1=t '.title', default: model_class.model_name.human.pluralize.titleize
table.table.table-striped
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:question)
      th= model_class.human_attribute_name(:answer)
      th= model_class.human_attribute_name(:state)
      th= model_class.human_attribute_name(:category_id)
      th= model_class.human_attribute_name(:created_at)
      th=t '.actions', default: t("helpers.actions")
  tbody
    - @chats.each do |chat|
      tr
        td= chat.id
        td= chat.question
        td= chat.answer
        td= chat.state
        td= chat.category_id
        td=l chat.created_at, format: :long
        td
          = link_to chat_path(chat), class: 'btn btn-xs', title: "#{ t('.show', default: t('helpers.links.show')) }" do
            = glyph 'info-sign'
          = link_to edit_chat_path(chat), class: 'btn btn-xs', title: "#{ t('.edit', default: t('helpers.links.edit')) }" do
            = glyph 'pencil'
          = link_to chat_path(chat), method: :delete, data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-xs', title: "#{ t('.destroy', default: t('helpers.links.destroy')) }" do
            = glyph 'remove'

= link_to t('.new', default: t("helpers.links.new")), new_chat_path, class: 'btn btn-primary'

app/views/chats/new.html.slim
- model_class = Chat
.page-header
  h1=t '.title', default: [:'helpers.titles.new', 'New %{model}'], model: model_class.model_name.human.titleize
= render partial: "form"

app/views/chats/show.html.slim
- model_class = Chat
div class="page-header"
  h1=t '.title', default: model_class.model_name.human.titleize

.fieldset
  dl
      dt.label.label-default= model_class.human_attribute_name(:question)
      dd
        pre.prettyprint= @chat.question
      dt.label.label-default= model_class.human_attribute_name(:answer)
      dd
        pre.prettyprint= @chat.answer
      dt.label.label-default= model_class.human_attribute_name(:state)
      dd
        pre.prettyprint= @chat.state
      dt.label.label-default= model_class.human_attribute_name(:category_id)
      dd
        pre.prettyprint= @chat.category_id

.form-group
  = link_to t('.back', default: t("helpers.links.back")), chats_path, class: 'btn btn-default'
  '
  = link_to t('.edit', default: t("helpers.links.edit")), edit_chat_path(@chat), class: 'btn btn-default'
  '
  = link_to t('.destroy', default: t("helpers.links.destroy")), chat_path(@chat), method: "delete", data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-danger'