config/routes.rb
Rails.application.routes.draw do
  resources :intents
  resources :entries
  resources :entities
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations" }

  resources :chats
  resources :companies
  resources :categories

  get  'invites/index' => 'invites#index', as: 'invites'
  post 'invites/invite' => 'invites#invite', as: 'invite'

  root 'pages#index'

  post '/chats/webhook' => 'chats#webhook'
end

app/models/category.rb
class Category < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :chats
  has_many :intent_user_says
  has_many :intent_responses
  accepts_nested_attributes_for :intent_user_says, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :intent_responses, reject_if: :all_blank, allow_destroy: true

  validates :name, presence: true, uniqueness: true

  serialize :contexts, Array
  serialize :templates, Array
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :set_api_ai_client, only: [:create, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    intent_request = @api_ai_client.create_intents_request
    response       = intent_request.create(param_options)
    contexts_templates  = { contexts: category_params[:contexts].split(","), templates: category_params[:templates].split(",") }
    @category = Category.new(category_params.merge(contexts_templates))

    respond_to do |format|
      if response.is_a?(Hash) && response[:status][:code].eql?(200)
        @category.intent_id = response[:id]

        if @category.save

          format.html { redirect_to @category, notice: 'Category was successfully created.' }
          format.json { render :show, status: :created, location: @category }
        else
          format.html { render :new }
          format.json { render json: @category.errors, status: :unprocessable_entity }
        end
      else
        @notice = response.message

        format.html { render :new }
        format.json { render json: { error: response.message }, status: response.code}
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|

      intent_request = @api_ai_client.create_intents_request
      response       = intent_request.update(@category.intent_id, param_options)

      if response.is_a?(Hash) && response[:status][:code].eql?(200)

        contexts_templates  = { contexts: category_params[:contexts].split(","), templates: category_params[:templates].split(",") }

        if @category.update(category_params.merge(contexts_templates))
          format.html { redirect_to @category, notice: 'Category was successfully updated.' }
          format.json { render :show, status: :ok, location: @category }
        else
          format.html { render :edit }
          format.json { render json: @category.errors, status: :unprocessable_entity }
        end
      else
        @notice = response.message

        format.html { render :new }
        format.json { render json: { error: response.message }, status: response.code}
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    intent_request = @api_ai_client.create_intents_request
    response       = intent_request.delete(@category.intent_id)

    # if response.is_a?(Hash) && response[:status][:code].eql?(200)
      @category.destroy
      respond_to do |format|
        format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
        format.json { head :no_content }
      end
    # else
    #   respond_to { |f|  f.html { redirect_to categories_url, notice: response.message } }
    # end
  end

  def param_options
    user_says_data = []
    responses = []

    if category_params[:intent_user_says_attributes].nil?
      category_params[:intent_user_says_attributes] = ""
    else
      category_params[:intent_user_says_attributes].each do |k, us|
        user_says_data << ApiAiRuby::UserSayData.new(us[:text], us[:alias], us[:meta])
      end
    end

    if category_params[:intent_responses_attributes].nil?
      category_params[:intent_responses_attributes] = ""
    else
      category_params[:intent_responses_attributes].each do |k, r|
        intent_aff_contexts = []
        intent_parameters   = []

        intent_aff_contexts_attr = r[:intent_affected_contexts_attributes] || Array.new
        intent_aff_contexts_attr.each do |kac, vac|
          intent_aff_contexts << ApiAiRuby::AffectedContext.new(vac[:name], vac[:lifespan])
        end

        intent_parameters_attr = r[:intent_parameters_attributes] || Array.new
        intent_parameters_attr.each do |kp, vp|
          intent_parameters << ApiAiRuby::Parameter.new(vp[:name], vp[:data_type], "\$" + vp[:value])
        end

        responses << ApiAiRuby::Response.new(
          "true",
          r[:action],
          intent_aff_contexts,
          intent_parameters,
          r[:speech])
      end
    end

    param_options = ApiAiRuby::Intent.new(
      category_params[:name],
      (category_params[:auto].eql?("1") ? true : false),
      [category_params[:name].downcase.tr(" ","-")],
      category_params[:templates].split(","),
      [ { "data": user_says_data } ],
      responses, 500000
    )

    param_options
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.friendly.find(params[:id])
    end

    def set_api_ai_client
      @api_ai_client = ApiAiRuby::Client.new(:client_access_token => ENV['API_AI_ACCESS'])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :auto, :priority, :contexts, :templates,
        intent_user_says_attributes: [:text, :alias, :meta, :id, :_destroy],
        intent_responses_attributes: [:reset_contexts, :action, :speech, :id, :_destroy,
          intent_affected_contexts_attributes: [:name, :lifespan, :id, :_destroy],
          intent_parameters_attributes: [:data_type, :name, :value, :id, :_destroy]]
      )
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.slim
- if @notice.present?
  .alert.alert-danger
    p = @notice

= simple_form_for @category, html: { class: "form-horizontal" }, wrapper: :horizontal_form, wrapper_mappings: { check_boxes: :horizontal_radio_and_checkboxes, radio_buttons: :horizontal_radio_and_checkboxes, file: :horizontal_file_input, boolean: :horizontal_boolean } do |f|

  = f.input :name, required: true
  = f.input :auto, as: :boolean, label: "Machine learning is on in this intent"
  = f.input :contexts,required: true, as: :string, input_html: { data: { role:'tagsinput' } }
  = f.input :templates,required: true, as: :string, input_html: { data: { role:'tagsinput' } }

  #intentUserSays
    = f.simple_fields_for :intent_user_says do |user_say|
      = render 'intent_user_say_fields', f: user_say

  .col-md-12
    = link_to_add_association 'Add User Say', f, :intent_user_says, class: "btn btn-sm btn-success"
    br
    br

  .clearfix

  #intentResponses
    = f.simple_fields_for :intent_responses do |response|
      = render 'intent_response_fields', f: response

  .col-md-12
    = link_to_add_association 'Add Response', f, :intent_responses, class: "btn btn-sm btn-success"
    br
    br

  .col-md-12
  	hr
    = f.submit "Save", class: 'btn btn-info'
    '
    = link_to t('.cancel', default: t("helpers.links.cancel")), categories_path, class: 'btn btn-default'

app/views/categories/_intent_affected_context_fields.html.slim
.nested-fields
	.page-header
		strong Intent affected context
	br
	= f.input :name
	= f.input :lifespan, as: :integer
	= link_to_remove_association "Remove affected context", f, class: "btn btn-sm btn-danger pull-right"

app/views/categories/_intent_parameter_fields.html.slim
.nested-fields
	.page-header
		strong Intent parameter
	br
	= f.input :data_type
	= f.input :name
	= f.input :value
	= link_to_remove_association "Remove parameter", f, class: "btn btn-sm btn-danger pull-right"

app/views/categories/_intent_response_fields.html.slim
.nested-fields
	.panel.panel-default
		.panel-heading Intent Bot Response
		.panel-body
		  = f.input :reset_contexts, as: :boolean, label: "Indicates that all contexts will be reset when this intent is triggered"
		  = f.input :action
		  = f.input :speech
		  = link_to_remove_association "Remove Response", f, class: "btn btn-sm btn-danger pull-right"

		  #intentAffectedContexts
		    = f.simple_fields_for :intent_affected_contexts do |affected_context|
		      = render 'intent_affected_context_fields', f: affected_context

		  .col-md-12
		   	= link_to_add_association 'Add Affected Context', f, :intent_affected_contexts, class: "btn btn-sm btn-success"
		   	br
		   	hr

		  #intentParameters
		    = f.simple_fields_for :intent_parameters do |parameter|
		      = render 'intent_parameter_fields', f: parameter

		  .col-md-12
		   	= link_to_add_association 'Add Parameter', f, :intent_parameters, class: "btn btn-sm btn-success"
		   	br
		   	br

app/views/categories/_intent_user_say_fields.html.slim
.nested-fields
	.panel.panel-default
		.panel-heading Intent user say
		.panel-body
		  = f.input :text
		  = f.input :alias
		  = f.input :meta
		  = link_to_remove_association "Remove", f, class: "btn btn-sm btn-danger pull-right"

app/views/categories/edit.html.slim
.page-header
  h1 Edit #{@category.name}

.row
	.col-md-12
		= render partial: "form"

app/views/categories/index.html.slim
.page-header
  h1 Intents

.row
  .col-md-12
    ul.list-group
      - @categories.each do |category|
        li.list-group-item
          strong= link_to category.name, category_path(category)

          .pull-right
            / = link_to 'Add Question', new_chat_path(category_id: category.id), class: "btn btn-sm btn-primary"
            = link_to category_path(category), class: 'btn btn-xs', title: "#{ t('.show', default: t('helpers.links.show')) }" do
              = glyph 'info-sign'
            = link_to edit_category_path(category), class: 'btn btn-xs', title: "#{ t('.edit', default: t('helpers.links.edit')) }" do
              = glyph 'pencil'
            = link_to category_path(category), method: :delete, data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-xs', title: "#{ t('.destroy', default: t('helpers.links.destroy')) }" do
              = glyph 'remove'

    hr
    = link_to "Add new Intent", new_category_path, class: 'btn btn-success'

app/views/categories/new.html.slim
.page-header
  h1 New category

.row
	.col-md-12
		= render partial: "form"

app/views/categories/show.html.slim
div class="page-header"
  h1

.fieldset
  dl
    dt.label.label-default Intent ID
    dd
      pre.prettyprint= @category.intent_id

  dl
    dt.label.label-default Name
    dd
      pre.prettyprint= @category.name

  dl
    dt.label.label-default Auto
    dd
      pre.prettyprint= @category.auto

  dl
    dt.label.label-default Contexts
    dd
      pre.prettyprint= @category.contexts

  dl
    dt.label.label-default Templates
    dd
      pre.prettyprint= @category.templates

  dl
    dt.label.label-default Priority
    dd
      pre.prettyprint= @category.priority

  dl
    dt.label.label-default User Says
    br

  - @category.intent_user_says.each do |user_say|
    dl
      dt.label.label-default Text
      dd
        pre.prettyprint= user_say.text
    dl
      dt.label.label-default Alias
      dd
        pre.prettyprint= user_say.alias
    dl
      dt.label.label-default Meta
      dd
        pre.prettyprint= user_say.meta


.form-group
  = link_to t('.back', default: t("helpers.links.back")), categories_path, class: 'btn btn-default'
  '
  = link_to t('.edit', default: t("helpers.links.edit")), edit_category_path(@category), class: 'btn btn-default'
  '
  = link_to t('.destroy', default: t("helpers.links.destroy")), category_path(@category), method: "delete", data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-danger'